services:
  app:
    image: nanawel/reciphpes
    container_name: reciphpes
    hostname: reciphpes
    restart: always
    ports:
      - 4569:80
    volumes:
      - ./data/var/www/webapp/var/db:/var/www/webapp/var/db:rw
      - ./data/var/www/webapp/var/log:/var/www/webapp/var/log:rw
     environment:
      APP_DEFAULT_LOCALE: en                       # default is "fr" for historical reasons
      APP_SET_LOCALE_FROM_ACCEPT_LANGUAGE: false   # default is true
      APP_SET_CONTENT_LANGUAGE_FROM_LOCALE: false  # default is true
