services:
  mysql:
    image: mysql
    restart: unless-stopped
    ports:
      - 3300:3306
    environment:
      MYSQL_DATABASE: mysql
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_ROOT_HOST: '%'

