services:
   web:
    image: leantime/leantime
    container_name: leantime
    hostname: leantime
    restart: always
    ports:
      - 80:80
    volumes:
      - ./data/var/www/html/public/userfiles:/var/www/html/public/userfiles     # Volume to store public files, logo etc
      - ./data/var/www/html/userfiles:/var/www/html/userfiles                   # Volume to store private user uploaded files
    environment:
      LEAN_DB_HOST: mysql_leantime
      LEAN_DB_USER: admin
      LEAN_DB_PASSWORD: 321.qwerty
      LEAN_DB_DATABASE: leantime
    depends_on:
      - db


   db:
    image: mysql
    container_name: mysql_leantime
    hostname: mysql_leantime
    restart: always
    volumes:
      - ./data/var/lib/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 321.qwerty
      MYSQL_DATABASE: leantime
      MYSQL_USER: admin
      MYSQL_PASSWORD: 321.qwerty
    command: --character-set-server=utf8 --collation-server=utf8_unicode_ci