services:
  roundcubemail:
    image: roundcube/roundcubemail:latest-fpm
    container_name: roundcubemail
    hostname: roundcubemail
    restart: unless-stopped
    ports:
      - 3420:9000
    volumes:
      # to install a plugin => docker compose exec -it roundcubemail composer require johndoh/contextmenu --update-no-dev
      - ./data/var/www/html:/var/www/html # the plugins installed persist here
      - ./data/var/roundcube/config:/var/roundcube/config
        #      - ./data//var/roundcube/db:/var/roundcube/db: # storage location of the SQLite database. Only needed if using ROUNDCUBEMAIL_DB_TYPE=sqlite to persist the Roundcube database.
        #      - ./data/tmp/roundcube-temp:/tmp/roundcube-temp: # Roundcube's temp folder. Temp files like uploaded attachments or thumbnail images are stored here. Share this directory via a volume when running multiple replicas of the roundcube container.
    environment:
      ROUNDCUBEMAIL_DB_TYPE: pgsql # Database provider; currently supported: mysql, pgsql, sqlite
      ROUNDCUBEMAIL_DB_HOST: roundcubedb
      ROUNDCUBEMAIL_DB_PORT: 5432
      ROUNDCUBEMAIL_DB_NAME: roundcube
      ROUNDCUBEMAIL_DB_USER: roundcube
      ROUNDCUBEMAIL_DB_PASSWORD: roundcube
      ROUNDCUBEMAIL_SKIN: elastic
      ROUNDCUBEMAIL_DEFAULT_HOST: tls://mail.example.org
      ROUNDCUBEMAIL_SMTP_SERVER: tls://mail.example.org
    depends_on:
      - roundcubedb


  roundcubedb:
    image: postgres
    container_name: roundcubedb
    hostname: roundcubedb
    restart: unless-stopped
    volumes:
      - ./data/var/lib//postgresql/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: roundcube
      POSTGRES_USER: roundcube
      POSTGRES_PASSWORD: roundcube


  roundcubenginx:
    image: nginx
    container_name: roundcubenginx
    restart: unless-stopped
    ports:
      - 9009:80
    volumes:
      - ./data/var/www/html:/var/www/html
      - ./data/etc/nginx/templates:/etc/nginx/templates
      - ./data/etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./data/etc/letsencrypt:/etc/letsencrypt
      - ./data/data/letsencrypt:/data/letsencrypt
    environment:
      NGINX_HOST: localhost  # set your local domain or your live domain
      NGINX_PHP_CGI: roundcubemail:9000  # same as roundcubemail container name
    depends_on:
      - roundcubemail

### Optional: add a full mail server stack to use with Roundcube like https://hub.docker.com/r/tvial/docker-mailserver
#   mailserver:
#     image: tvial/docker-mailserver:latest
#     hostname: mail.example.org
#     ...  # for more options see https://github.com/tomav/docker-mailserver#examples
