services:
  tolgee:
    image: tolgee/tolgee
    container_name: tolgee
    hostname: tolgee
    restart: unless-stopped
    ports:
      - 25432:25432
      - 8562:8080
    volumes:
      - ./data/data:/data
      - ./data/config.yaml:/config.yaml
    environments:
      spring.config.additional-location: file:///config.yaml
      TOLGEE_AUTHENTICATION_INITIAL_PASSWORD: admin
      TOLGEE_AUTHENTICATION_INITIAL_USERNAME: admin
      TOLGEE_AUTHENTICATION_JWT_SECRET: my_jwt_secret
      TOLGEE_MACHINE_TRANSLATION_GOOGLE_API_KEY: my_google_api_key
      TOLGEE_SMTP_AUTH: true
      TOLGEE_SMTP_FROM: Tolgee <no-reply@mydomain.com>
      TOLGEE_SMTP_HOST: email-smtp.regional-region.amazonaws.com
      TOLGEE_SMTP_PASSWORD: 
      TOLGEE_SMTP_PORT: 465
      TOLGEE_SMTP_SSL_ENABLED: true
      TOLGEE_SMTP_USERNAME: user@company.com
