services:
  heimdall:
    image: lscr.io/linuxserver/heimdall
    container_name: heimdall
    hostname: heimdall
    restart: unless-stopped
    ports:
      - 8741:80
      - 4410:443
    volumes:
      - ./data/config:/config
    environment:
      TZ: Africa/Cairo
      PUID: 1000
      PGID: 1000
      APP_NAME: Heimdall
      APP_ENV: local
      APP_KEY: 
      APP_DEBUG: false
      APP_URL: http://localhost
      LOG_CHANNEL: daily
      DB_CONNECTION: sqlite
      DB_DATABASE: app.sqlite
