services:
  tianji:
    image: moonrailgun/tianji
    container_name: tianji
    hostname: tianji
    restart: always
    ports:
      - 12345:12345
    environment:
      DATABASE_URL: postgresql://tianji:tianji@postgres:5432/tianji
      JWT_SECRET: replace-me-with-a-random-string
      ALLOW_REGISTER: false
      ALLOW_OPENAPI: true
    depends_on:
      - postgres


  postgres:
    image: postgres
    container_name: psotgres
    hostname: psotgres
    restart: always
    environment:
      POSTGRES_DB: tianji
      POSTGRES_USER: tianji
      POSTGRES_PASSWORD: tianji
    volumes:
      - ./data/var/lib/postgresql/data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5