services:
  rallly:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - 3565:3000
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres
      AUTH_REQUIRED: false
      ALLOWED_EMAILS: 
      DISABLE_LANDING_PAGE: false
      NEXT_PUBLIC_BASE_URL: http://localhost:3000
      SECRET_PASSWORD: 67b1623fc3f10e3d6c302d50d8342fe244b2702a95a00023cbb5fd7afe3cfd8d
      SUPPORT_EMAIL: foo@yourdomain.com
      SMTP_HOST: your-smtp-server
      SMTP_PORT: 587
      SMTP_SECURE: false
      SMTP_USER: your-smtp-user
      SMTP_PWD: your-smtp-password
      NODE_ENV: production


  postgres:
    image: postgres
    container_name: postgres
    hostname: postgres
    restart: always
    volumes:
      - ./data/var/lib/postgresql/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
