services:
  rustpad:
    image: ekzhang/rustpad
    container_name: rustpad
    hostname: rustpad
    restart: unless-stopped
    ports:
      - 3030:3030
    environment:
      PORT: 3030
      EXPIRY_DAYS: 1
      SQLITE_URI:
      RUST_LOG: DEBUG

