services:
  docassemble:
    image: jhpyle/docassemble
    container_name: docassemble
    hostname: docassemble
    # https://docassemble.org/docs/docker.html#tocAnchor-1-10-3
    ports:
      - 80:80
    volumes:
      - ./data/usr/share/docassemble/backup:/usr/share/docassemble/backup
    stop_grace_period: 5m
    # https://docassemble.org/docs/docker.html#configuration%20options
    environment:
      CONTAINERROLE: all
      DBPREFIX: postgresql+psycopg2://
      DBNAME: docassemble
      DBUSER: docassemble
      DBPASSWORD: abc123
      DBHOST: localhost
      USEHTTPS: false
      DAHOSTNAME: docassemble.example.com
      USELETSENCRYPT: false
      LETSENCRYPTEMAIL: 
      S3ENABLE: false
      S3ACCESSKEY: 
      S3SECRETACCESSKEY: 
      S3BUCKET: 
      S3REGION: 
      EC2: false
      TIMEZONE: America/New_York
