services:
  keycloak:
    image: keycloak
    container_name: keycloak
    restart: always
    links:
      - mariadb
    environment:
      - DB_VENDOR=mariadb
      - KC_DB_USERNAME=keycloak_user
      - KC_DB_PASSWORD=T4h9D1pE30CF4Qe/LUZkkg
      - KC_DB=mariadb
      - DB_ADDR=mariadb
      - DB_DATABASE=keycloak
      - DB_USER=keycloak_user
      - DB_SCHEMA=public
      - DB_PASSWORD=T4h9D1pE30CF4Qe/LUZkkg
      - KEYCLOAK_USER=admin
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=o8shsZ1ah21
      - KEYCLOAK_PASSWORD=o8shsZ1ah21
      - KEYCLOAK_FRONTEND_URL=https://keycloaksit.axispay.app
      - KEYCLOAK_PROXY_ADDRESS_FORWARDING=true
    #      - PROXY_ADDRESS_FORWARDING=true
    ports:
      - 9878:8080
    depends_on:
      - mariadb
