services:
  aptabase:
    image: ghcr.io/aptabase/aptabase
    container_name: aptabase
    hostname: aptabase
    restart: always
    ports:
      - 8000:80
    environment:
      BASE_URL: http://localhost:8000 # replace with your ip or domain, including port if needed
      AUTH_SECRET: c4rI4x8kz5DgKJ1is5Eiu9bNncSQ6ROD # get a strong secret from https://randomkeygen.com/
      DATABASE_URL: Server=aptabase_db;Port=5432;User Id=aptabase;Password=aptabase;Database=aptabase
      CLICKHOUSE_URL: Host=aptabase_events_db;Port=8123;Username=aptabase;Password=aptabase
    depends_on:
      - aptabase_events_db
      - aptabase_db


  aptabase_db:
    image: postgres
    container_name: aptabase_db
    hostname: aptabase_db
    restart: always
    volumes:
      - ./data/var/lib/postgresql/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: aptabase
      POSTGRES_PASSWORD: aptabase


  aptabase_events_db:
    image: clickhouse/clickhouse-server
    container_name: aptabase_events_db
    hostname: aptabase_events_db
    restart: always
    volumes:
      - ./data/var/lib/clickhouse:/var/lib/clickhouse
    environment:
      CLICKHOUSE_USER: aptabase
      CLICKHOUSE_PASSWORD: aptabase
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
