services:
  navidrome:
    image: deluan/navidrome
    container_name: navidrome
    hostname: navidrome
      #    user: 1000:1000 # should be owner of volumes
    restart: always
    ports:
      - 4533:4533
    volumes:
      - ./data/data:/data
      - ./data/music:/music:ro
    environment:
      # Optional: put your config options customization here. Examples:
      ND_SCANSCHEDULE: 1h
      ND_LOGLEVEL: info
      ND_SESSIONTIMEOUT: 24h
      ND_BASEURL: ""