services:
  pgadmin:
    image: dpage/pgadmin4
    container_name:  pgadmin
    hostname:  pgadmin
    restart: always
    ports:
      - 5011:80
    volumes:
      #- ./data/var/lib/pgadmin:/var/lib/pgadmin
      - pgadmin-data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: postgres
      PGADMIN_LISTEN_PORT: 80


volumes:
  pgadmin-data: