services:
 watchtower:
   image: containrrr/watchtower
   container_name: watchtower
   hostname: watchtower
   restart: unless-stopped
   security_opt:
     - no-new-privileges:true
   volumes:
     - /etc/timezone:/etc/timezone:ro
     - /etc/localtime:/etc/localtime:ro
     - /var/run/docker.sock:/var/run/docker.sock
     - ~/.docker/config.json:/config.json
   environment:
     WATCHTOWER_CLEANUP: true
     WATCHTOWER_LABEL_ENABLE: true
     WATCHTOWER_INCLUDE_RESTARTING: true
     WATCHTOWER_ROLLING_RESTARTING: true
     WATCHTOWER_POLL_INTERVAL: 120
     #WATCHTOWER_INCLUDE_STOPPED: true
     # SLACK
     WATCHTOWER_NO_STARTUP_MESSAGE: true
     WATCHTOWER_NOTIFICATIONS: slack
     WATCHTOWER_NOTIFICATION_SLACK_HOOK_URL: "https://hooks.slack.com/services/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"
     #WATCHTOWER_NOTIFICATION_SLACK_IDENTIFIER: watchtower-bot
    #  WATCHTOWER_NOTIFICATION_SLACK_CHANNEL: #my-custom-channel