services:
  admidio:
    image: admidio/admidio
    container_name: admidio
    hostname: admidio
    restart: unless-stopped
    ports:
      - 9895:8080
    volumes:
      - ./dat/var/www/admidio/adm_my_files:/var/www/admidio/adm_my_files
      - ./dat/var/www/admidio/adm_themes:/var/www/admidio/adm_themes
      - ./dat/var/www/admidio/adm_plugins:/var/www/admidio/adm_plugins
    environment:
      ADMIDIO_DB_TYPE: mysql
      ADMIDIO_DB_HOST: db:3306
      ADMIDIO_DB_NAME: admidio
      ADMIDIO_DB_USER: admidio
      ADMIDIO_DB_PASSWORD: secret-password
      # ADMIDIO_DB_TABLE_PRAEFIX: adm
      # ADMIDIO_MAIL_RELAYHOST: hostname.domain.at:25
      # ADMIDIO_LOGIN_FOR_UPDATE: 1
      # ADMIDIO_ORGANISATION: ADMIDIO
      # ADMIDIO_PASSWORD_HASH_ALGORITHM: DEFAULT
      # ADMIDIO_ROOT_PATH: https://www.mydomain.at/admidio
      # TZ: Africa/Cairo
      # HTTPD_START_SERVERS: 8
      # DOCUMENTROOT: /
      # PHP_MEMORY_LIMIT: 256M
      # ERROR_REPORTING: E_ALL & ~E_NOTICE
      # DISPLAY_ERRORS: ON
      # DISPLAY_STARTUP_ERRORS: OFF
      # TRACK_ERRORS: OFF
      # HTML_ERRORS: ON
