services:
  hbbs:
    image: rustdesk/rustdesk-server
    container_name: hbbs
    hostname: hbbs
    restart: unless-stopped
    ports:
      - 21115:21115
      - 21116:21116
      - 21116:21116/udp
      - 21118:21118
    volumes:
      - ./data/root:/root
    command: hbbs -r rustdesk.example.com:21117
    depends_on:
      - hbbr


  hbbr:
    image: rustdesk/rustdesk-server
    container_name: hbbr
    hostname: hbbr
    restart: unless-stopped
    ports:
      - 21117:21117
      - 21119:21119
    volumes:
      - ./data/root:/root
    command: hbbr