services:
  front:
    image: tombursch/kitchenowl-web
    container_name: kitchenowl-web
    hostname: kitchenowl-web
    restart: unless-stopped
    ports:
      - 5468:80
    depends_on:
      - back


  back:
    image: tombursch/kitchenowl
    container_name: kitchenowl
    hostname: kitchenowl
    restart: unless-stopped
    environment:
      JWT_SECRET_KEY: kjewofjior843j8344303434f8huvb
    volumes:
      - ./data/data:/data
