services:
  kimai:
    image: kimai/kimai2:fpm-dev
    restart: unless-stopped
    environment:
      ADMINMAIL: admin@kimai.local
      ADMINPASS: changemeplease
      DATABASE_URL: mysql://kimaiuser:kimaipassword@mysql/kimai
      TRUSTED_HOSTS: nginx,localhost,127.0.0.1
      memory_limit: 500M
      MAILER_URL: smtp://mailer:1025
      MAILER_FROM: kimai@example.com
    volumes:
      - public:/opt/kimai/public
      - ./data/opt/kimai/var:/opt/kimai/var
      # - ./ldap.conf:/etc/openldap/ldap.conf:z
      # - ./ROOT-CA.pem:/etc/ssl/certs/ROOT-CA.pem:z


  mysql:
    image: mysql
    restart: unless-stopped
    ports:
      - 3336:3306
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: kimai
      MYSQL_USER: kimaiuser
      MYSQL_PASSWORD: kimaipassword
      MYSQL_ROOT_PASSWORD: changemeplease
    healthcheck:
      test: mysqladmin -p$$MYSQL_ROOT_PASSWORD ping -h localhost
      interval: 20s
      start_period: 10s
      timeout: 10s
      retries: 3
    command: --default-storage-engine innodb


  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      PMA_ARBITRARY: 1


  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - 8080:8080
    volumes:
      - ./data/swagger.json:/swagger.json
    environment:
      SWAGGER_JSON: /swagger.json


  mailer:
    image: schickling/mailcatcher
    ports:
      - 1025:1025
      - 1080:1080



  nginx:
    image: tobybatch/nginx-fpm-reverse-proxy
    restart: unless-stopped
    ports:
      - 8001:80
    volumes:
      - ./data/opt/kimai/public:/opt/kimai/public:ro
    healthcheck:
      test:  wget --spider http://nginx/health || exit 1
      interval: 20s
      start_period: 10s
      timeout: 10s
      retries: 3
    depends_on:
      - kimai
