services:
  dozzle:
    image: amir20/dozzle
    container_name: dozzle
    hostname: dozzle
    restart: unless-stopped
    ports:
      - 9999:8080
    environment:
      DOZZLE_LEVEL: trace
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    healthcheck:
      test: [ "CMD", "/dozzle", "healthcheck" ]
      interval: 3s
      timeout: 30s
      retries: 5`1
      start_period: 30s