services:
  mysql:
    image: mysql
    container_name: mysql
    hostname: mysql
    restart: unless-stopped
    ports:
      - 5101:3306
    volumes:
      - ./data/var/lib/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE:
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_ALLOW_EMPTY_PASSWORD: false
      MYSQL_RANDOM_ROOT_PASSWORD: no
    cap_add:
      - SYS_NICE
    command: --default-authentication-plugin=mysql_native_password
