services:
  chartbrew:
    image: razvanilin/chartbrew
    container_name: chartbrew
    hostname: chartbrew
    restart: always
    ports:
      - 4018:4018
      - 4019:4019
    environment:
      CB_SECRET: 67b1623fc3f10e3d6c302d50d8342fe244b2702a95a00023cbb5fd7afe3cfd8d
      CB_API_HOST: 0.0.0.0
      CB_API_PORT: 4019
      CB_DB_HOST: mysql
      CB_DB_PORT: 3306
      CB_DB_NAME: chartbrew
      CB_DB_USERNAME: chartbrew
      CB_DB_PASSWORD: chartbrew
      REACT_APP_CLIENT_HOST: http://localhost:4018
      REACT_APP_API_HOST: http://localhost:4019
    depends_on:
      - mysql


  mysql:
    image: mysql
    container_name: mysql
    hostname: mysql
    restart: always
    volumes:
      - ./data/var/lib/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: chartbrew
      MYSQL_USER: chartbrew
      MYSQL_PASSWORD: chartbrew
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
