services:
  traggo:
    image: traggo/server
    container_name: traggo
    hostname: traggo
    restart: always
    ports:
      - 3030:3030
    volumes:
      - ./data/traggo/data:/opt/traggo/data
    environment:
    # the port the http server should use
      TRAGGO_PORT: 3030
    # default username and password
      TRAGGO_DEFAULT_USER_NAME: traggo
      TRAGGO_DEFAULT_USER_PASS: traggo

    # bcrypt password strength (higher = more secure but also slower)
    # TRAGGO_PASS_STRENGTH=10

    # how verbose traggo/server should log (must be one of: debug, info, warn, error, fatal, panic)
      TRAGGO_LOG_LEVEL: info

    # the database dialect (must be one of: sqlite3)
      TRAGGO_DATABASE_DIALECT: sqlite3

    # the database connection string, differs depending on the dialect
    # sqlite3:  path/to/database.db
    # TRAGGO_DATABASE_CONNECTION=data/traggo.db
