services:
  libretranslate:
    image: libretranslate/libretranslate
    container_name: libretranslate
    hostname: libretranslate
    restart: unless-stopped
    ports:
      - 5000:5000
    volumes:
      - ./data/app/db/:/app/db/
    environment:
      LT_API_KEYS_DB_PATH: /app/db/api_keys.db
    command: --ssl --ga-id MY-GA-ID --req-limit 100 --char-limit 500
    healthcheck:
      test: ['CMD-SHELL', './venv/bin/python scripts/healthcheck.py']
