services:
  uptime-kuma:
    image: louislam/uptime-kuma
    container_name: uptime-kuma
    hostname: uptime-kuma
    restart: unless-stopped
    security_opt:
      - no-new-privileges=true
    expose:
      - 3001
    volumes:
      - ./data/app/data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock:ro