services:
  mysql-workbench:
    image: lscr.io/linuxserver/mysql-workbench:latest
    container_name: mysql-workbench
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Cairo
    volumes:
      - ./data/config:/config
    ports:
      - 4520:3000
    cap_add:
      - IPC_LOCK
    restart: unless-stopped
