services:
  ergo:
    image: ghcr.io/ergochat/ergo
    container_name: ergo
    hostname: ergo
    restart: unless-stopped
    ports:
      - 6667:6667/tcp
      - 6697:6697/tcp
    volumes:
      - ./data/ircd:/ircd
