services:
  traduora:
    image: everco/ever-traduora
    container_name: traduora
    hostname: traduora
    restart: on-failure
    ports:
     - 5630:8080
    environment:
      TR_DB_TYPE: mysql
      TR_DB_USER: tr
      TR_DB_PASSWORD: change_me
      TR_DB_DATABASE: tr_dev
      TR_DB_HOST: mysqldb
      TR_DB_PORT: 3306
      NODE_ENV: development    
    entrypoint: ./docker-entrypoint.compose.sh
    depends_on:
      - mysqldb


  mysqldb:
    image: mysql
    container_name: mysql
    hostname: mysql
    restart: always
    environment:
      MYSQL_DATABASE: tr_dev
      MYSQL_USER: tr
      MYSQL_PASSWORD: change_me
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: true
