services:
  npm:
    image: jc21/nginx-proxy-manager
    container_name: npm
    hostname: npm
    restart: unless-stopped
    ports:
      - 80:80
      - 81:81
      - 443:443
    volumes:
      - ./data/data:/data
      - ./data/etc/letsencrypt:/etc/letsencrypt
    networks:
      - npm
    healthcheck:
      test: ["CMD", "/bin/check-health"]
      interval: 60s
      timeout: 30s




networks:
  npm:
    external: true
    name: npm